### ISSUE TITLE
Upgrade to react 18

### ISSUE THREAD

**Issue by mp3three** [mp3three/steggy#124]
Some dependencies aren't ready for the update yet, and all the types are a bit explodey right now. Try again in a few after things calm down

**Comment by ccontour** [comment]
Was able to make a code conversion, but the `antd` components were having a rough time of it. Drawers wouldn't open most of the time, and some of the select dropdowns were causing UI errors.

This commit contains the changes from the last attempt. Revisit again in a few weeks. This currently is blocking updates to NX, which REALLY REALLY wants to upgrade react

**Comment by mp3three** [comment]
22.29.1
